services:
  # Postgres for Airflow
  postgres-airflow:
    image: postgres:13
    container_name: postgres-airflow
    environment:
      POSTGRES_DB: airflow-db
      POSTGRES_USER: airflow-user
      POSTGRES_PASSWORD: airflow-password
    ports:
      - "5433:5432" # Change port to avoid conflicts
    restart: always

  # Postgres for dbt
  postgres-dbt:
    image: postgres:13
    container_name: postgres-dbt
    environment:
      POSTGRES_DB: dbt-db
      POSTGRES_USER: dbt-user
      POSTGRES_PASSWORD: dbt-password
    ports:
      - "5434:5432" # Change port to avoid conflicts
    restart: always

  #pgadmin for postgres-dbt
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-dbt
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  # Airflow
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-webserver
    depends_on:
      - postgres-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow-user:airflow-password@postgres-airflow:5432/airflow-db
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecretkey
    ports:
      - "8080:8080"
    restart: always
    entrypoint: ["/bin/bash", "-c", "airflow db init && airflow webserver"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock # Monter le socket Docker dans le conteneur Airflow


  # Airflow Scheduler
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler
    depends_on:
      - postgres-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow-user:airflow-password@postgres-airflow:5432/airflow-db
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecretkey
    restart: always
    entrypoint: ["airflow", "scheduler"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock # Monter le socket Docker dans le conteneur Airflow

  # dbt
  dbt:
    build: 
      context: .
      dockerfile: Dockerfile.dbt
    container_name: dbt
    depends_on:
      - postgres-dbt
    command: ["bash", "-c", "echo '⚙️  Starting dbt...' && dbt deps --profiles-dir profiles || true && dbt build --profiles-dir profiles || true && echo '✅ Done' && sleep infinity"]
    volumes:
      - ./dbt:/usr/app/dbt
      - ./dbt/profiles/profiles.yml:/root/.dbt/profiles.yml

volumes:
  pgadmin_data: