services:
  # Postgres for Airflow
  postgres-airflow:
    image: postgres:13
    container_name: postgres-airflow
    environment:
      POSTGRES_DB: airflow-db
      POSTGRES_USER: airflow-user
      POSTGRES_PASSWORD: airflow-password
    ports:
      - "5433:5432" # Change port to avoid conflicts
    restart: always

  # Postgres for dbt
  postgres-dbt:
    image: postgres:13
    container_name: postgres-dbt
    environment:
      POSTGRES_DB: dbt-db
      POSTGRES_USER: dbt-user
      POSTGRES_PASSWORD: dbt-password
    ports:
      - "5434:5432" # Change port to avoid conflicts
    restart: always

  #pgadmin for postgres-dbt
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-dbt
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  # Airflow
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-webserver
    depends_on:
      - postgres-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow-user:airflow-password@postgres-airflow:5432/airflow-db
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecretkey
    ports:
      - "8080:8080"
    restart: always
    entrypoint: ["/bin/bash", "-c", "airflow db init && airflow webserver"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data

  # Airflow Scheduler
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    depends_on:
      - postgres-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow-user:airflow-password@postgres-airflow:5432/airflow-db
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecretkey
    restart: always
    entrypoint: ["airflow", "scheduler"]
    volumes:
      - ./data:/opt/airflow/data

  # dbt
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt
    depends_on:
      - postgres-dbt
    command: ["run"]
    volumes:
      - ./dbt:/usr/app/dbt
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
    restart: always

volumes:
  pgadmin_data: